---
label: Config
hide_body: true
fields:
- type: text
  name: lang
  label: Language
- type: text
  name: title
  label: Site Title
  config:
    required: true
- type: text
  name: email
  label: Email
- type: text
  name: description
  label: Description
- type: text
  name: baseurl
  label: Baseurl
  description: The subpath of your site, e.g. /blog
  default: "/"
- type: text
  name: url
  label: URL
  description: The base hostname & protocol for your site, e.g. http://example.com
- type: field_group
  name: author
  label: Author
  fields:
  - type: text
    name: name
    label: Author Name
    config:
      required: true
  - type: text
    name: twitter
    label: Twitter Handle
  - type: file
    name: picture
    label: Author Picture
- type: text
  name: twitter_username
  label: Twitter Username
- type: text
  name: github_username
  label: GitHub Username
- type: file
  name: logo
  label: Site Logo
- type: boolean
  name: search
  label: Enable Search
  description: Places a site search next  to the site menu
  default: true
- type: boolean
  name: search_full_content
  label: Search Full Content
  default: true
- type: text
  name: search_provider
  label: Search Provider
  description: The service providing the site search
  default: algolia
- type: field_group
  name: algolia
  label: Algolia
  fields:
  - type: text
    name: application_id
    label: Application ID
    default: QB6HVGBSBA
  - type: text
    name: index_name
    label: Index Name
    default: basically-basic
  - type: text
    name: search_only_api_key
    label: Search Only API Key
    default: 9d5014e5bbc77372547bce778dfa5663
  - type: boolean
    name: powered_by
    label: Powered By
    default: true
- type: field_group
  name: liquid
  label: Liquid
  fields:
  - type: text
    name: error_mode
    label: Error Mode
    default: strict
- type: text
  name: markdown
  label: Markdown Type
  default: kramdown
- type: text
  name: theme
  label: Theme Name
  default: jekyll-theme-basically-basic
- type: list
  name: plugins
  label: Plugins
- type: field_group
  name: feed
  label: Feed
  fields:
  - type: text
    name: path
    label: Path
    default: atom.xml
- type: number
  name: paginate
  label: Paginate
  description: The number of entries allowed per page in pagination
  default: 10
  config:
    required: true
- type: text
  name: paginate_path
  label: Paginate Path
  hidden: true
- type: field_group
  name: collections
  label: Collections
  hidden: true
  fields:
  - type: field_group
    name: recipes
    label: Recipes
    fields:
    - type: boolean
      name: output
      label: Output
      default: true
    - type: text
      name: permalink
      label: Permalink
- type: field_group_list
  name: defaults
  label: Defaults
  hidden: true
  fields:
  - type: field_group
    name: scope
    label: Scope
    fields:
    - type: text
      name: path
      label: Path
      config:
        required: true
    - type: text
      name: type
      label: Type
      config:
        required: true
  - type: field_group
    name: values
    label: Values
    fields:
    - type: text
      name: layout
      label: Layout
    - type: boolean
      name: read_time
      label: Read Time
      default: true
